/**
 * Affiliate tracking helpers.
 *
 * CheapShark's redirect (https://www.cheapshark.com/redirect?dealID=...) routes through
 * THEIR affiliate links. To redirect commission to YOU, set tracking parameters per store
 * via env vars (REACT_APP_AFF_HUMBLE, REACT_APP_AFF_FANATICAL, etc.) and the helper below
 * will append them to the outbound URL. Most affiliate networks honor the parameter even
 * when prefixed by a redirect because they preserve query strings.
 *
 * For full guaranteed tracking, swap to deep-links generated by your affiliate network
 * (Awin, Impact, Sovrn) — set those full URLs in env and we'll use them instead.
 */

const PARTNERS = {
  "1":  process.env.REACT_APP_AFF_STEAM || "",      // Steam doesn't have a public affiliate program
  "3":  process.env.REACT_APP_AFF_GMG || "",        // Green Man Gaming
  "7":  process.env.REACT_APP_AFF_GOG || "",        // GOG
  "11": process.env.REACT_APP_AFF_HUMBLE || "",     // Humble Store (?partner=YOUR_ID)
  "15": process.env.REACT_APP_AFF_FANATICAL || "",  // Fanatical (?ref=YOUR_ID)
  "25": process.env.REACT_APP_AFF_EPIC || "",       // Epic
};

// Query-param key each store uses for partner tracking
const PARTNER_PARAM = {
  "3":  "tap_a",      // Green Man Gaming (placeholder — real network uses sjv.io)
  "7":  "as=",        // GOG uses Adtraction
  "11": "partner",    // Humble
  "15": "ref",        // Fanatical
};

const CHEAPSHARK_REDIRECT = "https://www.cheapshark.com/redirect";

export const dealUrl = (deal) => {
  const dealID = deal?.dealID;
  const storeID = String(deal?.storeID || "");
  const partner = PARTNERS[storeID];
  const key = PARTNER_PARAM[storeID];

  // Default: CheapShark redirect (works for all deals)
  const base = `${CHEAPSHARK_REDIRECT}?dealID=${dealID}`;

  if (partner && key) {
    // Append partner tracking. Some stores strip query strings on redirect, but Humble &
    // Fanatical preserve them. For guaranteed tracking, switch to a deep-link network URL.
    return `${base}&${key}=${encodeURIComponent(partner)}`;
  }
  return base;
};

export const hasAffiliatePartner = (storeID) => Boolean(PARTNERS[String(storeID)]);
